HDFS-908. TestDistributedFileSystem fails with Wrong FS on weird hosts
Description: On the same host where I experienced <a href="http://issues.apache.org/jira/browse/HDFS-874" title="TestHDFSFileContextMainOperations fails on weirdly configured DNS hosts">HDFS-874</a>, I also experience this failure for TestDistributedFileSystem:

<p>Testcase: testFileChecksum took 0.492 sec<br/>
  Caused an ERROR<br/>
Wrong FS: hftp://localhost.localdomain:59782/filechecksum/foo0, expected: hftp://127.0.0.1:59782<br/>
java.lang.IllegalArgumentException: Wrong FS: hftp://localhost.localdomain:59782/filechecksum/foo0, expected: hftp://127.0.0.1:59782<br/>
  at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:310)<br/>
  at org.apache.hadoop.fs.FileSystem.makeQualified(FileSystem.java:222)<br/>
  at org.apache.hadoop.hdfs.HftpFileSystem.getFileChecksum(HftpFileSystem.java:318)<br/>
  at org.apache.hadoop.hdfs.TestDistributedFileSystem.testFileChecksum(TestDistributedFileSystem.java:166)</p>

<p>Doesn't appear to occur on trunk or branch-0.21.</p>
Reason: bugfix
Author: Todd Lipcon
Ref: UNKNOWN