YARN-8919. Some tests fail due to NoClassDefFoundError for OperatorCreationException (tasanuma0829 via rkanter)
(cherry picked from commit 5e294e950b9d1b6f852f2d3467a9809a82f9860e)

Change-Id: I3122acafe40c09fb83407787e09d33d266124c2f